
name: Automatización CI/CD

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: agregar markdown
        uses: DavidAnson/markdownlint-cli2-action@v20

      - name: agregar archivo json
        run: markdownlint.json
