name: Automatización CI/CD

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: agregar markdown
        uses: DavidAnson/markdownlint-cli2-action@v20
        with: 
          config: .markdownlint-cli2.jsonc
